# Generated by CodiumAI
from pathlib import Path

import numpy as np

from vision_agent.tools.tools import save_video


class TestSaveVideo:
    def test_saves_frames_without_output_path(self):
        frames = [
            np.random.randint(0, 256, (480, 640, 3), dtype=np.uint8) for _ in range(10)
        ]
        output_path = save_video(frames)
        assert Path(output_path).exists()

    def test_saves_frames_with_output_path(self, tmp_path):
        frames = [
            np.random.randint(0, 256, (480, 640, 3), dtype=np.uint8) for _ in range(10)
        ]
        video_output_path = str(tmp_path / "output.mp4")
        output_path = save_video(frames, video_output_path)

        assert output_path == video_output_path
        assert Path(output_path).exists()
