name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    name: Linting & Unit Test
    strategy:
      matrix:
        python-version: [3.9, 3.11]
        os: [ ubuntu-22.04, windows-2022, macos-12 ]
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME_TAG: ci_job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.4.2
    - name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.in-project true
    - name: Print Python environment information
      run: |
        poetry env info
        poetry --version
        poetry run pip -V
    - name: Install dependencies
      run: |
        # Install main dependencies first so we can see their size
        poetry install --all-extras
    - name: Linting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --exclude .venv --count --show-source --statistics
    - name: Check Format
      run: |
        poetry run black --check --diff --color .
    - name: Type Checking
      run: |
        poetry run mypy vision_agent
    - name: Test with pytest
      run: |
        poetry run pytest -v tests/unit
