name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VISION_AGENT_API_KEY: ${{ secrets.VISION_AGENT_API_KEY }}
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  OPENAI_API_KEY: 123test
  PYTHONUTF8: 1

jobs:
  unit_test:
    name: Test
    strategy:
      matrix:
        python-version: [3.9, 3.11]
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME_TAG: ci_job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      shell: bash
      run: |
        pip install uv
        uv --version
    - name: Print Python environment information
      run: |
        uv run which python
        uv run python --version
        uv run pip --version
    - name: Install dependencies
      run: |
        # Install main dependencies first so we can see their size
        uv sync --all-extras
    - name: Linting
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --exclude .venv,examples,tests --count --show-source --statistics
    - name: Check Format
      run: |
        uv run black --check --diff --color vision_agent/
    - name: Type Checking
      run: |
        uv run mypy vision_agent
    - name: Test with pytest
      run: |
        uv run pytest -s -vvv tests/unit

  integ_test:
    name: Integration Test
    runs-on: ubuntu-22.04
    env:
      RUNTIME_TAG: ci_job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install uv
      shell: bash
      run: |
        pip install uv
        uv --version
    - name: Print Python environment information
      run: |
        uv run which python
        uv run python --version
        uv run pip --version
    - name: Install dependencies
      run: |
        # Install main dependencies first so we can see their size
        uv sync --all-extras
    - name: Test with pytest
      run: |
        uv run pytest -v tests/integ

  release:
    name: Release
    needs: unit_test
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):') && !contains(github.event.head_commit.message, '[skip release]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install uv
        shell: bash
        run: |
          pip install uv
          uv --version
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "yazhou.cao@landing.ai"
          - name: Bump up version
          run: |
            current_version=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)
            IFS='.' read -r major minor patch <<< "$current_version"
            patch=$((patch + 1))
            new_version="${major}.${minor}.${patch}"
            uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version "$new_version"
            git add pyproject.toml
            git commit -m "[skip ci] chore(release): ${new_version}"
            git push        
      - name: Publish to PyPI
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}